### PR TITLE
Added TLS support for Thrift [#19]

### LINKED ISSUE #19: TLS Support
I have a project that uses this library and it has wire-level encryption as a requirement and I would like to request TLS support be added.  I have started work on this with the goal of submitting it as a PR, however I have been running into issues.  My hope is that someone may be able to point me in the right direction.  Totally understand if this is not in scope for this project and feel free to close this if so, but wanted to give it a shot...

I have been able to get this to work in a test Scala project, but so far my attempts to translate this to Clojure have been in vain.  Below is what I have so far (I'm basing my implementation off the [TLS tests in Finagle](https://github.com/twitter/finagle/blob/finagle-6.33.0/finagle-thrift/src/test/scala/com/twitter/finagle/thrift/EndToEndTest.scala#L286)):

**Thrift File**
```
namespace java example.thrift

service TestService {
    string ping(1: string name)
}
```

**Service**
```clojure
(ns finagle-clj-tls.service
  (:import [example.thrift TestService]
           [com.twitter.finagle.transport Transport$TLSServerEngine]
           [com.twitter.finagle Service Thrift]
           [com.twitter.finagle.ssl Ssl]
           [com.twitter.finagle Service Stack$Param]
           [scala Tuple2 Option]
           [java.net InetSocketAddress InetAddress])
  (:require [finagle-clojure.futures :as f]
            [finagle-clojure.thrift :as thrift]
            [finagle-clojure.options :as options]
            [finagle-clojure.scala :as scala])
  (:gen-class))

(def cert-path "/path/to/cert.pem")

(def key-path "/path/to/private.key")

(defn make-service
  []
  (thrift/service TestService
    (ping [n] (f/value (str "Hello, " n "!")))))

(defn ^Stack$Param param [p]
  (reify Stack$Param
    (default [this] p)))

(defn ^Option optional-fn [v]
  (options/option (scala/Function0 v)))

(defn serve-tls [^InetSocketAddress addr ^Service service]
  (let [tls-engine (Transport$TLSServerEngine. (optional-fn (Ssl/server cert-path key-path nil nil nil)))]
    (->
      (Thrift/server)
      (.configured (Tuple2. tls-engine (param tls-engine)))
      (.serveIface addr service))))
```

**Client**
```clojure
(ns finagle-clj-tls.client
  (:import [example.thrift TestService TestService$ServiceIface]
           [com.twitter.finagle Stack$Param Thrift]
           [com.twitter.finagle.transport Transport$TLSClientEngine]
           [java.net InetSocketAddress]
           [com.twitter.finagle.ssl Ssl]
           [scala Tuple2])
  (:require [finagle-clojure.futures :as f]
            [finagle-clojure.thrift :as thrift]
            [finagle-clojure.options :as options]
            [finagle-clojure.scala :as scala]))

(defn ^Stack$Param param [p]
  (reify Stack$Param
    (default [this] p)))

(defn get-tls-engine []
  (Transport$TLSClientEngine.
    (options/option
      (scala/Function [inet]
        (if (instance? InetSocketAddress inet)
          (Ssl/clientWithoutCertificateValidation (.getHostName inet) (.getPort inet))
          (Ssl/clientWithoutCertificateValidation))))))

(defn get-tls-client [host port]
  (let [tls-client (get-tls-engine)]
    (->
      (Thrift/client)
      (.configured (Tuple2. tls-client (param tls-client)))
      (.newIface (str host ":" port) ^Class TestService$ServiceIface))))
```

This actually runs fine and I'm able to get responses, the problem is that they are not encrypted.  If you set up a packet capture (I'm using WireShark) you can see everything in plain text, however, with the Scala example I set up, the bytes are encrypted.

Thanks in advance.

### PR DESCRIPTION
**Pull request by manderson202**
This PR adds TLS support for Thrift.  This closes #19

### CODE REVIEW

**Comment by samn** [comment]
Awesome, thanks @manderson202! i'll review this ASAP

**Comment by samn** [comment]
This is great, thanks for contributing @manderson202! I'll try to get a release out this week with your changes :)

**Comment by samn** [comment]
@manderson202 released version 0.6.0 with TLS support for thrift

**Comment by manderson202** [comment]
Awesome, thanks @samn!

**Pull request merged**
